mv image24.png interview-documents.png
mv image11.png affinity-diagram.png
mv image26.png crit-session-feedback.png
mv image16.png persona-maggan.png
mv image21.png persona-jan.png
mv image10.png persona-vivi.png
mv image15.png scenario.png
mv image17.png worst-ideas-workshop.png
mv image20.png ideation-individual.png
mv image4.png ideation-overview.png
mv image27.jpg crit-pov-hmw.jpg
mv image14.png moodboard-wedding.png
mv image8.png moodboard-audio.png
mv image28.png moodboard-social.png
mv image1.png moodboard-ui.png
mv image13.jpg sketch-timeline-hearts.jpg
mv image18.jpg sketch-timeline-events.jpg
mv image29.jpg sketch-timeline-circles.jpg
mv image2.jpg wireframe-digital.jpg
mv image6.jpg wireframe-moment-detail.jpg
mv image9.jpg wireframe-gallery.jpg
mv image5.jpg wireframe-parallel-design.jpg
mv image3.jpg wireframe-add-flow.jpg
mv image12.jpg wireframe-parallel-03.jpg
mv image23.jpg app-flow-whiteboard.jpg
mv image19.jpg team-sketching.jpg
mv image25.jpg wireframe-discussion.jpg
mv image22.jpg user-testing.jpg
mv image7.jpg paper-prototype-testing.jpg
mv final-prototype-1.png hifi-timeline-add.png
mv final-prototype-2.png hifi-moment-view.png
mv final-prototype-3.png hifi-navigation.png
